version: "3.8"
services:
  web:
    # plein d'options, correspondant à celles qu'on peut trouver pour une commande run
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./src/critique_film:/app/src/critique_film
      - flask_migrations:/app/src/critique_film/migrations
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: empruntLivre
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  flask_migrations:
